---
name: Build Docker image

on:
  push:
    branches:
      - master

jobs:
  docker-image-builds:
    name: Docker image builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php_version: 7.3
            composer_version: 1
          - php_version: 7.3
            composer_version: 2

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: sudo apt-get install python3-setuptools
      - run: pip3 install jinja-cli 

      - name: Create PHP context directory
        run: (test ! -d "${{ matrix.php_version}}" && (echo "Creating ${{ matrix.php_version}} directory "; mkdir "${{ matrix.php_version}}") ) || echo "Directory ${{ matrix.php_version}} doesn't exists"

      - name: Generate Dockerfile
        run: ~/.local/bin/jinja -D php_version "${{ matrix.php_version }}" -D composer_version "${{ matrix.composer_version }}" Dockerfile.j2 > "${{ matrix.php_version }}/Dockerfile"
      - run: cat "${{ matrix.php_version }}/Dockerfile"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.php_version }}/
          file: ./${{ matrix.php_version }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heydon/drupal-builder:${{ matrix.composer_version }}-${{ matrix.php_version }}